# Generated by Django 2.2.4 on 2019-11-23 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_posts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posts',
            new_name='Post',
        ),
    ]
